# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# x.py
# Created on: 2015-09-15 19:02:08.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: x <Workspace> <Workday> 
# Description: 
# ---------------------------------------------------------------------------


import os, arcpy
from arcpy import env
from arcpy.sa import *

# Load required toolboxes
arcpy.ImportToolbox("C:/Program Files (x86)/ET SpatialTechniques/ET GeoWizards 11.1 for ArcGIS 10.2/ET GeoWizards.tbx")

# Script arguments
searchpath = os.getcwd()
outFile = open("06_fixWorkday_OUTPUT.txt", "w")
outFile.write(searchpath+"\n")

skipPaths = ["!workday","!points","!template","!testcode","!uniqvals","!points","!points_previous"]
skipData = ["Line_gen.shp","Point_ge.shp","PosnLine.shp"]

def inventory_data(workspace, datatypes):  
    for path, path_names, data_names in arcpy.da.Walk(workspace, datatype=datatypes, type=fcType):
        
        for skipPath in skipPaths:
            if skipPath in path_names:
                path_names.remove(skipPath)

        for skipDatum in skipData:
            if skipDatum in data_names:
                data_names.remove(skipDatum)
                # print "removed "+ skipDatum

        for data_name in data_names:
            yield os.path.join(path, data_name)
           

print "Processing "+searchpath+"..."
outFile.write("Processing "+searchpath+"...\n\n")


fcType = "Point"
countLayers = 0  

for fc in inventory_data(searchpath, "FeatureClass"):
    desc = arcpy.Describe(fc)
    typ = desc.shapeType
    name = desc.baseName
    head, folder = os.path.split(desc.path)
    
    if name == "Workday":
        
        if arcpy.Exists(desc.path+"\Workday1.shp"):       
            arcpy.Delete_management(desc.path+"\Workday1.shp")
        if arcpy.Exists(desc.path+"\Workday2.shp"):
            arcpy.Delete_management(desc.path+"\Workday2.shp")
        
        print "Changing "+folder+"..."
        outFile.write("Changing "+folder+"...\n")
        
        # Local variables:
        outfile1 = desc.path+"\Workday1.shp"
        outfile2 = desc.path+"\Workday_new.shp"
        
        # Process: Rename Total_Mix_ to Total_USED
        arcpy.gp.toolbox = "C:/Program Files (x86)/ET SpatialTechniques/ET GeoWizards 11.1 for ArcGIS 10.2/ET GeoWizards.tbx";
        arcpy.gp.ET_GPRedefineFields(fc, outfile1, "Total_Mix_ Total_USED 7 2; AGT_APP_RT x 8 0")
        
        # Process: Add Field AGT_APP_RT as Float
        arcpy.AddField_management(outfile1, "AGT_APP_RT", "FLOAT", "7", "2", "", "", "NULLABLE", "NON_REQUIRED", "")
        
        # Process: Calculate Field
        arcpy.CalculateField_management(outfile1, "AGT_APP_RT", "str(!x!).split(\"%\")[0]", "PYTHON_9.3", "")
        
        # Process: Order Fields
        arcpy.gp.toolbox = "C:/Program Files (x86)/ET SpatialTechniques/ET GeoWizards 11.1 for ArcGIS 10.2/ET GeoWizards.tbx";
        arcpy.gp.ET_GPOrderFields(outfile1, outfile2, "Recorder;TREAT_PLAN;Workgroup;Workgroup2;SNAME;Work_Desc;TREAT_TYPE;TRADE_NM;AGT_APP_RT;ADJ_TRADE_;ADJ_AGT_AP;Total_USED;Max_PDOP;Max_HDOP;Corr_Type;Rcvr_Type;GPS_Date;GPS_Time;Update_Sta;Feat_Name;Datafile;Unfilt_Pos;Filt_Pos;Data_Dicti;GPS_Week;GPS_Second;GNSS_Heigh;Vert_Prec;Horz_Prec;Std_Dev;Northing;Easting;Point_ID;Folder")
        
        if arcpy.Exists(desc.path+"\Workday1.shp"):       
            arcpy.Delete_management(desc.path+"\Workday1.shp")
        if arcpy.Exists(desc.path+"\Workday2.shp"):
            arcpy.Delete_management(desc.path+"\Workday2.shp")
        
        countLayers += 1
 
print "\nProcessed " + str(countLayers) + " layers."
outFile.write("\nProcessed " + str(countLayers) + " layers.")

outFile.close()    # This closes the text file